development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:2e38855c39ec0877033ddb689cb7f817@barb.redistogo.com:10262/
  channel_prefix: question_queue_production
